name 'dmlb2000_desktop'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dmlb2000_desktop'
long_description 'Installs/Configures dmlb2000_desktop'
version '0.1.2'

depends 'dmlb2000_chef'
depends 'dmlb2000_chefdk'
depends 'dmlb2000_pipeline'
depends 'dmlb2000_users'
depends 'dmlb2000_distro'
